# create a docker-compose.yml file
version: “2”
 services:
  web:
   image: olaniranolaolujames/usermanager
   environment:
    - PORT=3000
    -   DB_URL=mongodb://usermanager:usermanager1@ds159856.mlab.com:59856/usermanager
   build: .
   volumes:
     — ./:/app
   ports:
   — “3000:3000”
   links:
    — mongo
   mongo:
    image: mongo
    ports:
      — “27017:27017”