# create a docker-compose.yml file
 version: '3'
 services:
  web:
   image: usermanager
   environment:
    - PORT=9000
    -   DB_URL=mongodb://admin:admin@ds159856.mlab.com:59856/usermanager
   build: .
   volumes:
     - ./:/app
     - /usr/src/app/node_modules
   depends_on:
     - 'mongo'
   ports:
     - "9000:9000"
   links:
     - mongo
  mongo:
    image: "mongo"
    ports:
     - "27017:27017"
      
  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
     - "1234:1234"